org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=rearm
mod.name=ReArm
mod.group=me.pajic
mod.version=2.4.20
mod.channel_tag=
mod.authors=pajic
mod.contributors=Lufurrius, Moonkey
mod.license=MIT
mod.description=Remunition and Armament
mod.sources_url=https://github.com/pajicadvance/rearm
mod.homepage_url=https://modrinth.com/mod/rearm
mod.issues_url=https://github.com/pajicadvance/rearm/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.mixson=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]

publish.modrinth=NHzN2FGz
publish.curseforge=1130102
publish.github=false
