org.gradle.jvmargs=-Xmx4G
parchment_version=[VERSIONED]
org.gradle.parallel=true
org.gradle.caching=true
loader_version=0.17.2
mod_version = 2.3.4
maven_group = me.pajic
archives_base_name = rearm
fabric_version=[VERSIONED]
mixinconstraints_version=1.1.0
fzzy_version=[VERSIONED]
mixson_version=v1.4.0
modmenu_version=[VERSIONED]
emi_version=[VERSIONED]
enchdesc_version=[VERSIONED]